### PR TITLE
Add missing install_requires

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by matthiask** [comment]
Just a question: How does this help? Won't Django be a dependency of all projects anyway? Why does it have to be specified explicitly?

**Comment by georgek** [comment]
This package imports from Django, therefore Django is a requirement. It helps because then tools like pip can ensure you have a consistent environment.

**Comment by matthiask** [comment]
That's right, but I'd assume that Django is installed anyway.

I think that upgrading just one package (e.g. `pip install -U django-js-asset`) also upgrades all its dependencies. Upgrading Django itself in this case isn't very helpful, especially if you're not using the newest Django release (major or minor, not patch release) everywhere. There are ways around that and you should be using wheels and rebuilding virtualenvs anyway, but still.

So I still don't see the benefit of adding Django to `install_requires` (except for purity) and I see some minor downsides. Which makes me want to reject this contribution even though it's a contribution from a first-time contributor to this repository.

**Comment by georgek** [comment]
By default pip doesn't upgrade dependencies. The option is `--upgrade-strategy` and the default is `only-if-needed` (ie. it only updates the dependencies if they are required by the upgraded package).

**Comment by matthiask** [comment]
Alright, maybe this has changed in the meantime. I'm convinced. Thanks all!

**Pull request merged**
